CircleCI-Public/gcp-cli-orb

.circleci/config.yml, src/commands/install.yml
https://github.com/CircleCI-Public/gcp-cli-orb/issues/9
> Because the image caches can be out of date, the first `sudo apt update` will fail on building a circleci job using an old image
([link](https://github.com/circleci/circleci-images/pull/378#issuecomment-504963660))
- remove apt lists
- also bump orb-tools
=> remove apt lists

.circleci/config.yml, src/commands/install.yml
This work was needed for progressing the Google Clour Run orb.
When attempting to use the command(s) `gcloud components install beta && gcloud components update` the following error is presented.
```
gcloud components install beta && gcloud components update
ERROR: (gcloud.components.install) 
You cannot perform this action because the Cloud SDK component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 
sudo apt-get install google-cloud-sdk
```
This appears to be a result of using the "interactive" CLI which is installed via `apt-get` which was called out in this Stack-Overflow: https://stackoverflow.com/questions/42697026/install-google-cloud-components-error-from-gcloud-command
Google recommends installing …
=> Install from Versioned non-interactive CLI

src/commands/install.yml
A customer said this curl command often failed to download files, so I added a retry option.
And also, -S option is to show error messages for the curl command.
I've confirmed, when the curl download file from `https://dl.google.com`, it fails one in ten times.
> https://app.circleci.com/pipelines/github/ganezasan/circleci-sandbox/3200/workflows/a54f5b29-4c28-41cc-811a-db6ebf461a55
And also, I compared with `wget` command, and it always successful because of the retry option. The default retry option in`wget` is 20.
> https://www.gnu.org/software/wget/manual/wget.html
After adding the retry option, I ran it 60 times and it all worked.
> https://app.circleci.com/pipelines/github/ganezasan/circleci-sandbox/3201/workflows/20a97484-801e-4957-aeed-416e733dd0d9
=> [semver:patch] Add --retry and -S option

src/@orb.yml, src/commands/initialize.yml, src/commands/install.yml, src/executors/default.yml, src/executors/google.yml, src/executors/machine.yml, src/jobs/install_and_initialize_cli.yml
v2 update. Contains changes around copy and executors. See the related GitHub Milestone: https://github.com/CircleCI-Public/gcp-cli-orb/milestone/1
=> V2 [semver:major]

src/commands/initialize.yml, src/jobs/install_and_initialize_cli.yml
Fixes Issue: https://github.com/CircleCI-Public/gcp-gke-orb/issues/9
Support GOOGLE_COMPUTE_REGION for gcloud CLI
=> [semver:minor] Support GOOGLE_COMPUTE_REGION environment variable

src/@orb.yml
`orb-tools/check-env-var-param` command doesn't properly work at the current orb version,  and it doesn't ensure all the environment variables exist. This issue has fixed in a newer version.  So I'll update `orb-tools` version `8.26.0` to `9.3.1`, so the following PR has applied and fixed the issue.
> https://github.com/CircleCI-Public/orb-tools-orb/pull/74
Here is the test to confirm the newer verison of `orb-tools` ensure all the environment valiables exist.
https://app.circleci.com/pipelines/github/ganezasan/circleci-sandbox/3550/workflows/c51b24fe-578d-40e7-9644-18ff835adaab/jobs/8519
=> [semver:patch] upgrade orb-tool to fix check-env-var-param issue

src/jobs/install_and_initialize_cli.yml
Make `version` configurable on the `install_and_initialize_cli` job
- [ x] All new jobs, commands, executors, parameters have descriptions
- [ x] Examples have been added for any significant new features
- [ x] README has been updated, if necessary
This allows for specifying a custom version of the gcloud CLI when using the combined `install_and_initialize_cli` job, rather than needing to call the commands separately.
Add `version` passthrough parameter to `install_and_initialize_cli`
=> [semver:minor] Add version as job parameter

src/commands/initialize.yml
Fixes #38
The changes in #23 make the initialize command fail if one of `GOOGLE_COMPUTE_ZONE` or `GOOGLE_COMPUTE_REGION` is not set. While having one of these set implicitly may be useful for some people, it is not required for all commands, and can also usually be specified via `--zone`, `--region`, or `--location` explicitly as well. This also updates docs to make some parameter docs clearer.
Make initialize succeed even if neither of `GOOGLE_COMPUTE_ZONE` or `GOOGLE_COMPUTE_REGION` are set.
This will also enable _both_ to be set if both of the env vars exist.
Clarify docs:
- Clarify when it's the env var name vs. the value to use
- Clarify wording so it's clear that these are the _default_ values for the CLI to use
=> [semver:minor] make GOOGLE_COMPUTE_{REGION,ZONE} optional

src/commands/initialize.yml
It's pretty typical to disable these features in Docker and CI, since they presumably are not that useful, and could also slow things down or add additional output.
I'm not sure if it needs to be done before `gcloud version` runs in the install step, but I think this should be Ok (it's out of date now, and `gcloud version` doesn't seem to report that).
set `core/disable_usage_reporting` and `component_manager/disable_update_check` in gcloud
=> [semver:patch] disable update check and usage reporting

src/commands/install.yml
Update gcloud CLI to 363.0.0
picked from #35 with original attribution to its author
=> [semver:minor] Update the default `gcloud` version to 363.0.0

src/jobs/install_and_initialize_cli.yml
- **N/A** _All new jobs, commands, executors, parameters have descriptions_
- **N/A** _Examples have been added for any significant new features_
- **N/A** _README has been updated, if necessary_
The current default for the Google Cloud SDK (283.0.0) is over 2 years old at this point and is no longer available to download. This updates the version to a current release (383.0.0) [[changelog](https://cloud.google.com/sdk/docs/release-notes)].
```
$ curl -i https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-283.0.0
HTTP/2 404 
content-length: 1449
content-type: text/html; charset=utf-8
server: downloads
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
date: Tue, 03 May 2022 01:20:34 GMT
```
Bumps default Google Cloud SDK version to …
=> fix: Bump default Google Cloud SDK to 383.0.0

.circleci/test-deploy.yml, src/commands/install.yml, src/commands/setup.yml, src/scripts/install.sh, src/scripts/setup.sh
Provide the user access to Install gcloud components between gcloud installation and initialization
Added optional `components` parameter to `setup` and `install` commands. Space separate component ids to install multiple. See https://cloud.google.com/sdk/docs/components for additional info.
=> feat: Added components parameter to install and setup commands

.circleci/test-deploy.yml, src/scripts/install.sh
The archived links https://cloud.google.com/sdk/docs/downloads-versioned-archives are now using `cli` instead of `sdk` after version 370
Added logic to resolve URL before installation
=> fix: future proof installation url being changed

src/scripts/install.sh
- Downloading the CLI to the project directory prevents `checkout` steps from running. They fail with:
```
Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository
```
- Closes #62 
This PR changes the installation directory from `~/project` to a temporary folder created with `mktemp`. I opted out of using `/usr/local`, `/usr/bin` and `/opt` because these require root permission for changes, adding a hard dependency on `sudo` for Alpine.
=> fix: change installation path

.circleci/test-deploy.yml, src/scripts/install.sh
This PR closes #70 by addressing an issue where the Google Cloud SDK installation fails with an error related to a corrupt tar archive. This problem prevents users from successfully installing and using the Google Cloud SDK in their projects.
This PR modifies the installation script to introduce two new functions, `download_and_extract()` and `download_with_retry()`. These functions improve the process of downloading and extracting the Google Cloud SDK tar file by implementing retries when download failures occur.
The `download_and_extract()` function is responsible for downloading the tar file and extracting it to the specified installation directory. The `download_with_retry()` function wraps around the `download_and_extract()` function and retries the download process up to three times …
=> feat: retry download when decompression fails

src/scripts/install.sh
Closes #73 
This PR adds an extra check for the CLI installation. If the installed version is newer than whatever is retrieved from the release notes, we skip the installation.
=> fix: skip installation if installed version is newer

.circleci/test-deploy.yml, src/executors/default.yml, src/scripts/install.sh
* Support Windows as a platform
* Modify the tested update versions to account for the inability of versions < `456.0.0` to work with Python >= 3.12
Adds support to run the orb on Windows machine executors.
Remove the reliance on `sudo`, and support the built-in `sort` binary differences between *nix and WIndows
=> Windows support

src/scripts/install.sh
Submitted in #84 by @tadashi0713 to prevent interactive prompt from stalling jobs until timeout.
Adds `--quiet` flag to `gcloud components install` command for unattended use cases.
=> chore: add --quiet flag for installing gcloud components

.circleci/test-deploy.yml, src/scripts/install.sh
From https://github.com/CircleCI-Public/gcp-cli-orb/pull/90
This orb incorrectly installs a Linux version of the gcloud CLI on Windows executors. This results in problems such as errors with subsequent docker builds and pushes to Google Artifact Registry.
Perhaps addresses https://github.com/CircleCI-Public/gcp-cli-orb/issues/81.
When running the install command on a Windows executor, download the gcloud CLI archive that was made for Windows.
=> fix: Install correct gcloud CLI archive on Windows: (see PR #90)

src/commands/setup.yml
Hi. This orb has always helped me!!
When orbs was upgraded from v2 to v3, it now calls the install command inside gcp-cli/setup as well, which causes failure uninstall step when use an image which gcloud is installed. (We used image based on google/cloud-sdk:alpine, work around it by installing the sudo command, but we don't want to reinstall itself). 
It is helpful that gcp-cli/install runs automatically, but it would be more convenient to have the ability to skip.
Add parameter `skip_install` in  `gcp-cli/setup` command
=> Add parameter skip_install to gcp-cli/setup

.circleci/test-deploy.yml, src/commands/install.yml, src/scripts/install.sh
Currently this orb installs a gcloud binary and components.
In some scenarios users only want to install components and want to reuse the currently installed gcloud binary from the executor or docker image.
This PR adds a new parameter to the `install` command called `skip_installation` which is a boolean that allows to skip installation of glcoud and only runs the installation of the specified gcloud components.
=> Orb tries to install the latest CLI version, even though it's already in the image #80
